#!/usr/bin/env python3
"""Generate frozen comparison data from hash-checked upstream inputs.

Usage: python3 internal/names/generate.py SOURCE_DIRECTORY
The directory contains vfs_unicode.c, vfs_unicode_data.h, vfs_utfconvdata.h and
UCStringCompareData.h from the revisions inventoried in docs/sources.json.
Apple's scalar normalizer is compiled only during generation. Portable builds
use the resulting Go data, without C, host Unicode libraries or network access.
"""
import hashlib
from pathlib import Path
import re
import subprocess
import sys
import tempfile

HASHES = {
    "vfs_unicode.c": "c92023ff31f0008de6f00c23ac33c3d8388b2588ba2eed91471ef51fabaf325d",
    "vfs_unicode_data.h": "69443aa4aeb34e0faf7790219d3dda1b3b4c3d13f05341ff2154f1501587eacd",
    "vfs_utfconvdata.h": "696f99ae7235aad56b3af6201b482bda7530e422bda92aafeb9d59d280b4c032",
    "UCStringCompareData.h": "88773669ce79ebe2d6bcc84d3341c3c2586e649984ac97453adb1b8706440464",
}


def array(source, name):
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
    match = re.search(re.escape(name) + r"\[\]\s*=\s*\{([^}]+)\}", source, re.S)
    if not match:
        raise ValueError("missing C array " + name)
    return [int(n.strip(), 0) for n in match[1].split(",") if n.strip()]


def quoted(points):
    return '"' + ''.join(f"\\U{c:08x}" for c in points) + '"'


def emit(name, mapping, value_type):
    result = f"var {name} = map[rune]{value_type}{{\n"
    for key, value in sorted(mapping.items()):
        literal = quoted(value) if value_type == "string" else str(value)
        result += f"0x{key:x}: {literal},\n"
    return result + "}\n\n"


def main():
    directory = Path(sys.argv[1])
    sources = {}
    for name, digest in HASHES.items():
        data = (directory / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != digest:
            raise ValueError("upstream hash mismatch: " + name)
        sources[name] = data.decode()
    out = Path(__file__).parent
    header = "// Code generated by generate.py; DO NOT EDIT.\n"
    apple = sources["vfs_unicode.c"]
    start = apple.index("STATIC_UNLESS_TEST\nint32_t\nnormalizeOptCaseFoldU32Char(")
    shim = '''#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include "vfs_unicode_data.h"
#define STATIC_UNLESS_TEST static
static int32_t adjustCase(bool, int32_t, int32_t *);
static uint8_t getCombClassU32Char(int32_t);
static int32_t decomposeHangul(int32_t, int32_t *);
'''
    main_c = '''
int main(void) {
 for (int sensitive=0; sensitive<=1; sensitive++) {
  for (int32_t c=0; c<=0x10ffff; c++) {
   if ((c>=0xd800 && c<=0xdfff) || (c>=0xac00 && c<=0xd7a3)) continue;
   int32_t chars[4]; uint8_t classes[4]={0};
   int n;
   if (c<128) { chars[0]=sensitive?c:nfBasicCF[c]; n=1; }
   else { n=normalizeOptCaseFoldU32Char(c, sensitive, chars, classes); }
   if (n<0) continue;
   if (n==0 || n>4) return 1;
   if (n==1 && chars[0]==c && classes[0]==0) continue;
   printf("%d %d", sensitive,c);
   for (int i=0;i<n;i++) printf(" %d %d", chars[i],classes[i]);
   printf("\\n");
  }
 }
 return 0;
}
'''
    with tempfile.TemporaryDirectory(prefix="apple-name-tables-") as temporary:
        work = Path(temporary)
        (work / "vfs_unicode_data.h").write_text(sources["vfs_unicode_data.h"])
        (work / "emit.c").write_text(shim + apple[start:] + main_c)
        subprocess.run(["cc", "-std=c99", "-O2", str(work / "emit.c"), "-o", str(work / "emit")], check=True)
        rows = subprocess.check_output([str(work / "emit")], text=True).splitlines()
    maps = [[], []]
    for row in rows:
        values = list(map(int, row.split()))
        units = ','.join('{'+str(c)+','+str(cc)+'}' for c, cc in zip(values[2::2], values[3::2]))
        maps[values[0]].append(f"0x{values[1]:x}: {{{units}}},\n")
    notice = sources["vfs_unicode_data.h"].split("*/", 1)[0] + "*/\n"
    generated = header + notice + apple.split("*/", 1)[0] + "*/\n"
    generated += "// Modified 2026-10-09: materialized Apple's Unicode 16 scalar mappings and combining classes.\n"
    generated += "// SPDX-License-Identifier: APSL-2.0\n// Licenses: LICENSES/. Sources: docs/sources.json.\npackage names\n\n"
    for index, name in enumerate(["apfsFolded", "apfsSensitive"]):
        generated += f"var {name} = map[rune][]unit{{\n" + ''.join(maps[index]) + "}\n\n"
    (out / "apfs_tables.go").write_text(generated)

    source = sources["vfs_utfconvdata.h"]
    pairs = array(source, "__CFUniCharDecompositionTable")
    table = dict(zip(pairs[::2], pairs[1::2]))
    multiple = array(source, "__CFUniCharMultipleDecompositionTable")
    bitmap = array(source, "__CFUniCharDecomposableBitmap")
    properties = array(source, "__CFUniCharCombiningPropertyBitmap")
    latin = array(sources["UCStringCompareData.h"], "gLatinCaseFold")
    lower = array(sources["UCStringCompareData.h"], "gLowerCaseTable")
    decomp, classes, folds = {}, {}, {}

    def expand(c):
        if c not in table:
            return [c]
        value = table[c]
        length, offset = (value >> 12) & 7, value & 0xfff
        sequence = [offset] if length == 1 else multiple[offset:offset+length]
        return expand(sequence[0]) + sequence[1:] if value & 0x8000 else sequence

    for c in range(65536):
        page = bitmap[c >> 8]
        decomposable = page == 255 or (page and bitmap[256 + (page - 1) * 32 + (c & 255)//8] & (1 << (c % 8)))
        if decomposable and not 0xac00 <= c <= 0xd7a3:
            decomp[c] = expand(c)
            if decomp[c] == [c]:
                raise ValueError(f"unresolved Apple decomposition {c:x}")
        page = properties[c >> 8]
        cls = properties[page * 256 + (c & 255)] if page else 0
        if cls:
            classes[c] = cls
        page = lower[c >> 8]
        fold = latin[c] if c < 256 else (lower[page + (c & 255)] if page else c)
        if fold != c:
            folds[c] = fold
    # Preserve both upstream copyright/license headers with the derived data.
    notices = source[:source.index("*/")+2] + "\n" + sources["UCStringCompareData.h"].split("*/", 1)[0] + "*/\n"
    (out / "hfs_tables.go").write_text(header + notices +
        "// Copyright (c) 1997-1999 Apple Inc. All rights reserved.\n"
        "// Modified 2026-10-09: flattened Apple C tables into Go maps.\n"
        "// SPDX-License-Identifier: APSL-2.0\n// License: LICENSES/APSL-2.0.txt. Sources: docs/sources.json.\n"
        "package names\n\n" + emit("hfsDecomposition", decomp, "string")
        + emit("hfsClass", classes, "uint8") + emit("hfsFold", folds, "rune"))
    subprocess.run(["gofmt", "-w", str(out / "apfs_tables.go"), str(out / "hfs_tables.go")], check=True)


if __name__ == "__main__":
    main()
